blank_issues_enabled: false
contact_links:
  - name: Questions on GitHub Discussions
    url: https://github.com/pegasus-isi/kiso-plankifier-experiment/discussions
    about: Ask questions about your own experiments on the Discussions tab.
  - name: Questions on Slack or Email
    url: https://pegasus.isi.edu/contact
    about: Ask questions about your own experiments on our Slack.
